### ISSUE TITLE
User Story Template #1 

### ISSUE THREAD

**Issue by Gerrit-Sch** [Gerrit-Sch/capstone-project#1]
## Value Proposition

**As a ** ...(user, author, logged-in user...)
I need ...(describe the goal)
to be able to ...(describe the reason)

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] describe every scenario in detail
- [ ] e.g. All Inputs are required, show warning if empty.
- [ ] ...

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
