### ISSUE TITLE
Landing page.md

### ISSUE THREAD

**Issue by Gerrit-Sch** [Gerrit-Sch/capstone-project#2]
## Value Proposition

**As a ** user
I need ...to insert an area code
to be able to ...get a list of real estate areas for area code provided

## Description

![Untitled-2022-03-24-1612(1)](https://user-images.githubusercontent.com/98734377/159951163-d545b41d-1161-47b0-a0a5-fe9f51d6e18a.png)

## Acceptance Criteria

- [ ] input element only accepts German area code format (5 numbers)
- [ ] otherwise error alert will pop up
- [ ] on click all real estate offers for the corresponding area code are displayed

## Tasks

(for developers team)

- [ ] create a branch "landing-page"
- [ ] create component "input"
- [ ] create component "button"
- [ ] create specs for "input"
- [ ] create specs for "button"
- [ ] Update styles
