### ISSUE TITLE
Bookmark function

### ISSUE THREAD

**Issue by Gerrit-Sch** [Gerrit-Sch/capstone-project#3]
## Value Proposition

**As a ** ...user
I need ...to bookmark my favourite listings
to be able to ...group them in a separate view

## Description

![Untitled-2022-03-25-1527(1)](https://user-images.githubusercontent.com/98734377/160360172-8006aa35-3094-4d33-92ba-6ed1fb290ddb.png)

## Acceptance Criteria

- [ ] bookmark item that can be toggled is visible on each listing
- [ ] bookmark item is  unticked by default
- [ ] all bookmarked items are rendered on a separate site
- [ ] upon untoggling the bookmark item, the items disappear from the bookmark section

## Tasks

- [ ] all listings have to be rendered with a bookmark item that can be toggled
- [ ] implement bookmark logic
- [ ] create corresponding specs
- [ ] implement react router

**Comment by PReichetanz** [comment]
If you want to see your bookmarked cards in a separate view, you need to show here how the bookmarked page should look like.

In your value proposition, please leave out the dots ... and rather use **bold** text.
