### ISSUE TITLE
Add function and navigation

### ISSUE THREAD

**Issue by Gerrit-Sch** [Gerrit-Sch/capstone-project#4]
## Value Proposition

As a **user**
I need **to add listings**
to be able to **offer rental propositions to other users**

## Description

![Untitled-2022-03-28-1115(1)](https://user-images.githubusercontent.com/98734377/160367793-a37ee2ca-04cf-4936-ba09-84761c60ae1b.png)

![Untitled-2022-03-28-1127(2)](https://user-images.githubusercontent.com/98734377/162728571-eea7e646-5adb-4da4-b972-b1356aed57e1.png)

## Acceptance Criteria

- [x] all Inputs are required, show warning if empty.

## Tasks

- [x] add navigation component
- [x] create forms labels and inputs for title, rental price, square meters area code and description

- [x] implement submit logic
